# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelf_app.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='items', to='shelf_app.User'),
        ),
    ]
